[package]
name = "imp"
version = "0.1.0"
authors = ["rnp39 <rnp39@cornell.edu>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.7"

[dependencies]
codespan = "0.1.3"
clap = { version = "3.1.12", features = ["derive"] }
lalrpop-util = "0.19.7"
peeking_take_while = "1.0.0"
